spring: 
    profiles: 
        active:
           - dev
---
spring:
    profiles: dev
    application:
        name: dept-config-bj1901-dev
---
spring:
    profiles: test
    application:
        name: dept-config-bj1901-test