spring: 
    profiles: 
        active:
           - dev
---
server:
  port: 9000
spring:
  profiles: dev
  application:
    name: eureka-server-dev
eureka:
  #instance:
    #hostname: localhost
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己
    fetch-registry: false           #false表示自己就是注册中心，职责是维护实例，不参加检索
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
  instance:
    #prefer-ip-address: true
    #ip-address: 127.0.0.1
---
server:
  port: 9000
spring:
    profiles: test
    application:
        name: eureka-server-test
eureka:
  #instance:
    #hostname: localhost
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己
    fetch-registry: false           #false表示自己就是注册中心，职责是维护实例，不参加检索
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
  instance:
    #prefer-ip-address: true
    #ip-address: 127.0.0.1