server:
  port: 8082
  servlet:
    context-path: /dept8082
spring:
  application:
    name: dept-consumer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
      #defaultZone: http://127.0.0.1:9000/eureka,http://127.0.0.1:9001/eureka