server:
  port: 8081
  servlet:
    context-path: /dept8081
mybatis:
  type-aliases-package: com.bj1901.api.domain
spring:
  application:
    name: dept-server						#微服务最重要的是取名字！微服务对外暴露的名字
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/db1             # 数据库名称
    username: root
    password: root
logging:
  level:
    com.bj1901.provider.dao: debug
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
      #defaultZone: http://127.0.0.1:9000/eureka,http://127.0.0.1:9001/eureka
  instance:
    instance-id: dept-server		#修改别名
    prefer-ip-address: true		#显示IP地址
info:
  app.name:  dept-server
  company.name:  com.bj1901
  build.artifactId:  $project.artifactId$
  build.version:  $project.version$